🌟 catalogue avec barre de recherche
IGNF/cartes.gouv.fr-entree-carto pull request #245
Opened 2024-06-24 13:39 UTC by IGNFhc

## Pull request checklist

Verifiez que votre Pull Request remplit les conditions suivantes :
- [ ] Des tests ont été ajoutés pour les changements (corrections de bugs ou features)
- [ ] De la documentation a été mise à jour ou ajoutée si nécessaire (corrections de bugs ou features)
- [ ] Un build (`npm run build`) a été lancé localement et s'est correctement déroulé
- [ ] Les exemples impactés par les modifications (`npm run samples`) ont été testés et validés localement
- [ ] Les tests (`npm run test`) sont passés localement

## Type de Pull request

 

 

Quel type de changement cette Pull Request introduit-elle :
- [ ] Bugfix
- [x] Feature
- [ ] Mise à jour du style du code (syntaxe, renommage de fonctions)
- [ ] Refactoring (lisibilité/performance du code, sans changements fonctionnels)
- [ ] Changement sur le processus de build
- [ ] Contenu de la documentation
- [ ] Autres (décrire ci-après) : 

## Quel est le comportement actuel (avant PR) :

Numéro du ticket : N/A

## Quel est le nouveau comportement :

- Ajout d'une barre de recherche dans le catalogue
- Ajout d'onglet (carte thématiques, ...) pour le moment pas de règles disponible pour trier donc même résulats dans les trois onglets
- Ajout d'accordéon pour trier les couches par thématiques

## Cette PR introduit-elle des breaking changes ?

- [ ] Oui
- [x] Non

## Autres informations

2024-08-08 15:10 UTC, elias75015 requested changes
Quand on veut rajouter une couche de base : on a cette erreur : 
![image](https://github.com/user-attachments/assets/5f3962fd-643f-4e68-aac6-07bed1f2dfb9)
![image](https://github.com/user-attachments/assets/93d5ead6-8ce8-4488-8a42-e22ed12406a9)

Le nom des couches et le menu dépasse :
![image](https://github.com/user-attachments/assets/cfe052b6-b39a-446d-970f-6bd808d5c22c)

2024-09-02 13:34 UTC, lowzonenose commented
Grrr..., certaines descriptions sont en HTML..., pénible
![image](https://github.com/user-attachments/assets/5df811e1-547b-4304-bb27-20f9d1f5c832)

2024-09-05 13:21 UTC, azarz commented
![image](https://github.com/user-attachments/assets/9324c1c3-6162-4994-b17f-90acf8ecb0f2)
Souci de css ?

2024-09-05 13:30 UTC, azarz commented
Trouvé : c'est à cause de `-webkit-fill-available`, à chaque fois ajouter `-moz-available` :
```css
.toto {
  width: -webkit-fill-available;
  width: -moz-available
}
```

Perso je ne recommande pas ce genre de propriété no standard css, j'aurais préféré un calc(), par exemple pour `catalogue-container` : 
```css
.catalogue-container {
  width: calc(10% - 60px);
}
```

2024-09-05 13:54 UTC, azarz approved these changes

2024-09-05 14:01 UTC, IGNFhc commented
Merci Amaury j'avais oublié ce point

2024-09-12 09:30 UTC, lowzonenose commented
je ne suis pas fan que la **scrollbar** englobe les onglets et les radio boutons :
![image](https://github.com/user-attachments/assets/3acee980-c095-45ef-843b-b4d6a2c27b2a)

je pense que la **scrollbar** est uniquement pour la liste des couches

2024-09-12 09:31 UTC, lowzonenose requested changes
cf. commentaire https://github.com/IGNF/cartes.gouv.fr-entree-carto/pull/245/#issuecomment-2345749189

2024-09-12 12:35 UTC, lowzonenose requested changes
J'ai commencé à renseigner la jsdoc sur le catalogue.
Peux tu compléter le reste ?

2024-09-13 08:45 UTC, IGNFhc commented
@lowzonenose est ce que ça te va si on valide cette branche catalogue et je m'occupe de la doc des autres composants sur une autre branche ?

2024-09-16 09:03 UTC, lowzonenose approved these changes
On documente les classes, et on analyse les performances pour une prochaine fois (tickets à mettre en place).

2024-09-26 10:31 UTC, merged