Feat/interaction
IGNF/cartes.gouv.fr-entree-carto pull request #259
Opened 2024-07-08 08:37 UTC by IGNFhc

## Pull request checklist

Verifiez que votre Pull Request remplit les conditions suivantes :
- [ ] Des tests ont été ajoutés pour les changements (corrections de bugs ou features)
- [ ] De la documentation a été mise à jour ou ajoutée si nécessaire (corrections de bugs ou features)
- [ x] Un build (`npm run build`) a été lancé localement et s'est correctement déroulé
- [ ] Les exemples impactés par les modifications (`npm run samples`) ont été testés et validés localement
- [ ] Les tests (`npm run test`) sont passés localement

## Type de Pull request

 

 

Quel type de changement cette Pull Request introduit-elle :
- [ ] Bugfix
- [ ] Feature
- [ ] Mise à jour du style du code (syntaxe, renommage de fonctions)
- [ ] Refactoring (lisibilité/performance du code, sans changements fonctionnels)
- [ ] Changement sur le processus de build
- [ ] Contenu de la documentation
- [ ] Autres (décrire ci-après) : 

## Quel est le comportement actuel (avant PR) :

Numéro du ticket : N/A

## Quel est le nouveau comportement :

- get feature info pour les layers ajoutés a la carte
-
-

## Cette PR introduit-elle des breaking changes ?

- [ ] Oui
- [ ] Non

## Autres informations

2024-07-08 09:12 UTC, elias75015 commented
Côté extension, c'est la classe ".gp-feature-info-div" qui stylise la pop-up.

Il faudra faire évoluer le control getFeatureInfo des extensions pour rendre la pop-up conforme en mode DSFR (utilisation du fichier getFeatureInfoDSFR.css  ?)

Sinon, fonctionnellement, décalage entre le clic et l'affichage de la pop-up. 
Ci-dessous, j'ai cliqué sur la Sarcellerie, et la pop-up s'affiche en dessous :+1: 
![image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/b3e20f6a-7207-48db-ad90-52e7f8070a84)


 L'affichage d'un marker temporaire sur la position pointée pourrait également être pertinent (à retirer dès que la pop-up disparait)

2024-07-08 09:14 UTC, elias75015 requested changes
Côté extension, c'est la classe ".gp-feature-info-div" qui stylise la pop-up.

Il faudra faire évoluer le control getFeatureInfo des extensions pour rendre la pop-up conforme en mode DSFR (utilisation du fichier getFeatureInfoDSFR.css  ?)

Sinon, fonctionnellement, décalage entre le clic et l'affichage de la pop-up. 
Ci-dessous, j'ai cliqué sur la Sarcellerie, et la pop-up s'affiche en dessous : 
![image](https://github.com/IGNF/cartes.gouv.fr-entree-carto/assets/6764800/b3e20f6a-7207-48db-ad90-52e7f8070a84)


 L'affichage d'un marker temporaire sur la position pointée pourrait également être pertinent (à retirer dès que la pop-up disparait)

2024-07-08 10:20 UTC, lowzonenose commented
du coup, pour résumer :
Sur l'extension, on vire la condition d'ajout des couches à interroger, on interroge toutes les couches !
Et, on corrige aussi le problème de positionnement sur la grille (ex. position:bottom-left)

En évolution, on est aussi en attente sur la décision d'une maquette pour savoir si il ne serait pas mieux d'afficher les informations dans un menu au lieu d'une popup (via une option)

2024-07-08 10:23 UTC, lowzonenose commented
@IGNFhc 
```js
var feature =  new GetFeatureInfo({
      options :{
         position : "top-right"
      }
});
```

2024-07-08 15:00 UTC, lowzonenose approved these changes
:heavy_check_mark:  positionnement + ajout auto des couches

En attente d'une maquette sur le choix d'une popup ou d'un menu...

2024-08-19 17:38 UTC, elias75015 commented
La maquette est dispo sur le figma : fenêtre fixe.

Faire évoluer cette PR (ou nouvelle PR) pour coller à la maquette.

2024-09-25 16:21 UTC, elias75015 commented
Géré côté extensions : https://github.com/IGNF/geopf-extensions-openlayers/pull/169

2024-09-25 16:21 UTC, closed without merging