🚧 maj du menu selon maquette
IGNF/cartes.gouv.fr-entree-carto pull request #273
Opened 2024-07-18 09:36 UTC by IGNFhc

## Pull request checklist

Verifiez que votre Pull Request remplit les conditions suivantes :
- [ ] Des tests ont été ajoutés pour les changements (corrections de bugs ou features)
- [ ] De la documentation a été mise à jour ou ajoutée si nécessaire (corrections de bugs ou features)
- [ ] Un build (`npm run build`) a été lancé localement et s'est correctement déroulé
- [ ] Les exemples impactés par les modifications (`npm run samples`) ont été testés et validés localement
- [ ] Les tests (`npm run test`) sont passés localement

## Type de Pull request

 

 

Quel type de changement cette Pull Request introduit-elle :
- [ ] Bugfix
- [ ] Feature
- [ ] Mise à jour du style du code (syntaxe, renommage de fonctions)
- [ ] Refactoring (lisibilité/performance du code, sans changements fonctionnels)
- [ ] Changement sur le processus de build
- [ ] Contenu de la documentation
- [ ] Autres (décrire ci-après) : 

## Quel est le comportement actuel (avant PR) :

Numéro du ticket : N/A

## Quel est le nouveau comportement :

- le menu correspond à la maquette (en position absolu par dessus la carte)
-
-

## Cette PR introduit-elle des breaking changes ?

- [ ] Oui
- [ ] Non

## Autres informations

2024-07-19 22:08 UTC, lowzonenose reviewed
ça dépasse ! 
![image](https://github.com/user-attachments/assets/1da23d31-511b-4e5a-b709-c060f67b5a3b)

Se caler avec la PR #283 pour modifier le bouton
![image](https://github.com/user-attachments/assets/b9e620cf-00b7-42c1-87a0-5adcd317c1ad)

Aprés, je ne connais pas la maquette...

2024-07-22 08:36 UTC, IGNFhc commented
> ça dépasse ! ![image](https://private-user-images.githubusercontent.com/10401006/350586059-1da23d31-511b-4e5a-b709-c060f67b5a3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mzc1NTQsIm5iZiI6MTcyMTYzNzI1NCwicGF0aCI6Ii8xMDQwMTAwNi8zNTA1ODYwNTktMWRhMjNkMzEtNTExYi00ZTVhLWI3MDktYzA2MGY2N2I1YTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA4MzQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkOGU1NGI0MmY5YTcxNzhmMzVhNTY2MzI4ZGI4OWMwYzU2NDE0Yjk1NmViNmJjOGM4ZWI3N2I2Zjk4ZmI5ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wXFIkes4KiY8BiH-2ARx-o5A4oUPZxrJsr-FwqgrqV4)
> 

C'est étrange je n'ai pas du tout de dépassement chez moi

2024-07-22 14:01 UTC, elias75015 commented
Alors : 
- je n'ai pas le bouton du menu de droite chez moi comme sur le screenshot de JP. D'ailleurs je pensais que cette PR ne concernait que le menu de gauche des widgets.
- le passage dark/light theme (et vis-versa) casse le rendu du menu
- le wording est à changer : "Gestion d'outils" d'après la maquette
- il faudrait confirmer auprès de @Kristell-5 le rendu des widgets à la droite de l'écran quand le menu est déplié
![image](https://github.com/user-attachments/assets/59a504a4-e487-488a-b98b-3c0bc3a8a41d)

Il y a une bande verticale grise complétement à droite, alors que dans le fonctionnement actuel la carte apparait en fond. 
De plus, quand le menu se déplie, les autres widgets du coin inférieur droit semblent se décaler à gauche avec la carte en fond ?

2024-07-24 08:37 UTC, elias75015 commented
Problème de style sur le bouton "fermer" du menu : 
![image](https://github.com/user-attachments/assets/43bf7958-887b-44ae-abf3-d743cef40393)

A traiter pour les deux thèmes (light/dark)

2024-07-24 09:13 UTC, elias75015 requested changes
Voir mes derniers commentaires

2024-07-29 13:30 UTC, lowzonenose approved these changes

2024-07-30 08:55 UTC, elias75015 approved these changes
OK pour moi sous réserve de la résolution du conflicted file.

2024-07-31 13:09 UTC, merged