Feature/profil alti
IGNF/cartes.gouv.fr-entree-carto pull request #325
Opened 2024-10-02 14:12 UTC by IGNFhc

## Pull request checklist

Verifiez que votre Pull Request remplit les conditions suivantes :
- [ ] Des tests ont été ajoutés pour les changements (corrections de bugs ou features)
- [ ] De la documentation a été mise à jour ou ajoutée si nécessaire (corrections de bugs ou features)
- [ ] Un build (`npm run build`) a été lancé localement et s'est correctement déroulé
- [ ] Les exemples impactés par les modifications (`npm run samples`) ont été testés et validés localement
- [ ] Les tests (`npm run test`) sont passés localement

## Type de Pull request

 

 

Quel type de changement cette Pull Request introduit-elle :
- [ ] Bugfix
- [ ] Feature
- [ ] Mise à jour du style du code (syntaxe, renommage de fonctions)
- [ ] Refactoring (lisibilité/performance du code, sans changements fonctionnels)
- [ ] Changement sur le processus de build
- [ ] Contenu de la documentation
- [ ] Autres (décrire ci-après) : 

## Quel est le comportement actuel (avant PR) :

Numéro du ticket : N/A

## Quel est le nouveau comportement :

-
-
-

## Cette PR introduit-elle des breaking changes ?

- [ ] Oui
- [ ] Non

## Autres informations

2024-10-02 14:13 UTC, IGNFhc commented
Attente de résolution de cette issue
https://github.com/IGNF/geopf-extensions-openlayers/issues/179

2024-10-09 16:09 UTC, lowzonenose requested changes
On est en attente de l'icone sur le profil altimétrique, mais aussi du style de la saisie.

Je pense que le style par défaut n'est pas applicable sur le site.
Les options pour changer les styles : 
 * @param {Object} [options.stylesOptions] - styles management
 * @param {Object} [options.stylesOptions.marker = {}] - styles management of marker displayed on map when the user follows the elevation path. Specified with an {@link https://openlayers.org/en/latest/apidoc/module-ol_style_Image-ImageStyle.html ol.style.Image} subclass object
 * @param {Object} [options.stylesOptions.draw = {}] - styles used when drawing. Specified with following properties.
 * @param {Object} [options.stylesOptions.draw.pointer = {}] - Style for mouse pointer when drawing the line. Specified with an {@link https://openlayers.org/en/latest/apidoc/module-ol_style_Image-ImageStyle.html ol.style.Image} subclass object.
 * @param {Object} [options.stylesOptions.draw.start = {}] - Line Style when drawing. Specified with an {@link https://openlayers.org/en/latest/apidoc/module-ol_style_Stroke-Stroke.html ol.style.Stroke} object.
 * @param {Object} [options.stylesOptions.draw.finish = {}] - Line Style when finished drawing. Specified with an {@link https://openlayers.org/en/latest/apidoc/module-ol_style_Stroke-Stroke.html ol.style.Stroke} object.

2024-10-09 16:09 UTC, lowzonenose commented on src/components/carte/control/ElevationPath.vue
> +<script setup lang="js">
On ajoute les événements : 
* @fires elevationpath:drawstart
 * @fires elevationpath:drawend
 * @fires elevationpath:compute

2024-10-09 16:09 UTC, lowzonenose commented on src/components/carte/Controls.vue
> +  v-if="controlOptions"
indentation

2024-10-10 10:10 UTC, lowzonenose commented on src/composables/controls.js
> +    label: 'Profil altimétrique',
je ne comprends pas cette méthode  : `useControlsMenuOptions()`
pourquoi ne pas mettre les informations (hint et label) dans l'objet `useControls` ?

2024-10-15 14:33 UTC, elias75015 commented
> Attente de résolution de cette issue [IGNF/geopf-extensions-openlayers#179](https://github.com/IGNF/geopf-extensions-openlayers/issues/179)

C'est résolu

2024-10-17 09:37 UTC, IGNFhc commented
@lowzonenose j'ai ajouté les évènements. 
Pour les remarques sur le composables controls.js ça doit faire l'objet d'une autre PR

2024-10-18 09:00 UTC, elias75015 commented
@lowzonenose t'es OK ?

2024-10-22 17:01 UTC, merged