🚑 fix: corrections sur le composant de partage
IGNF/cartes.gouv.fr-entree-carto pull request #329
Opened 2024-10-03 15:53 UTC by IGNFhc

## Pull request checklist

Verifiez que votre Pull Request remplit les conditions suivantes :
- [ ] Des tests ont été ajoutés pour les changements (corrections de bugs ou features)
- [ ] De la documentation a été mise à jour ou ajoutée si nécessaire (corrections de bugs ou features)
- [ ] Un build (`npm run build`) a été lancé localement et s'est correctement déroulé
- [ ] Les exemples impactés par les modifications (`npm run samples`) ont été testés et validés localement
- [ ] Les tests (`npm run test`) sont passés localement

## Type de Pull request

 

 

Quel type de changement cette Pull Request introduit-elle :
- [ ] Bugfix
- [ ] Feature
- [ ] Mise à jour du style du code (syntaxe, renommage de fonctions)
- [ ] Refactoring (lisibilité/performance du code, sans changements fonctionnels)
- [ ] Changement sur le processus de build
- [ ] Contenu de la documentation
- [ ] Autres (décrire ci-après) : 

## Quel est le comportement actuel (avant PR) :

Numéro du ticket : N/A

## Quel est le nouveau comportement :

- modif objet et corps du mail
- partage de lien via post linked in / facebook / x
-

## Cette PR introduit-elle des breaking changes ?

- [ ] Oui
- [ ] Non

## Autres informations

2024-10-09 15:52 UTC, lowzonenose requested changes

2024-10-09 15:52 UTC, lowzonenose commented on src/stores/mapStore.js
> +    return `${url}?c=${center.value}%26z=${Math.round(zoom.value)}%26l=${layers.value}%26w=${controls.value}%26permalink=yes`;
non, je ne suis pas fan !
le permalien ne devrait pas être encodé à ce niveau là.
tu encodes au niveau de la classe Share.

2024-10-09 15:52 UTC, lowzonenose commented on src/components/carte/control/Share.vue
> +  ? { scale: defaultScale.value, name: icon }
hummm..., **defaultScale** n'est pas une ref !?

2024-10-09 15:52 UTC, lowzonenose commented on src/components/carte/control/Share.vue
> +    {
indentation !

2024-10-09 15:52 UTC, lowzonenose commented on index.html
> +    <meta property="og:url" content="https://cartes.gouv.fr-entree-carto/"/>
Je dirais que pour la production, on a : `https://cartes.gouv.fr/cartes`
Ce paramètre est dynamique selon l'env de déploiement..., il devrait donc être généré au moment du build.
Voir du côté de **Vite**

2024-10-11 10:35 UTC, elias75015 commented
Les widgets ajoutés à la carte ne sont pas enregistrés dans le code de l'iframe

2024-10-11 10:44 UTC, elias75015 commented
Pour les partages :

- LinkedIn et Facebook : ouvre la fenêtre de partage, mais il n'y a pas de permalien dans le contenu :yellow_circle: 
- Instagram : ouvre la page IGN France :yellow_circle: 
- X (Twitter): OK :green_circle: 
- Mail : OK sauf destinataire, il faut enlever l'adresse geoplateforme@ign.fr :yellow_circle: 

- copie permalien : OK :green_circle: 
- iframe : il manque les widgets ajoutés à la carte :yellow_circle:

2024-10-11 10:47 UTC, elias75015 commented
Le widget permalien étant déjà poussé sur la main, il serait pertinent de pousser rapidement les première corrections réalisées dans cette PR. Le RAF pourra être fait dans la foulée.

@JP qu'en penses-tu ? (par contre je ne vois pas trop comment reporter proprement dans une issue les remontées faites ici...)

2024-10-11 13:36 UTC, elias75015 commented
Reste à faire (retours JP + Elias) consignés sur le ticket https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/340 attribué à Hector

2024-10-11 13:40 UTC, merged