Connexion à l'espace utilisateur
IGNF/cartes.gouv.fr-entree-carto pull request #361
Opened 2024-10-31 18:54 UTC by lowzonenose

2024-12-06 16:42 UTC, elias75015 commented
![image](https://github.com/user-attachments/assets/55c1e197-0a21-4620-9fe2-c7963b35c983)
Une fois connecté, ce n'est pas mon nom qui apparait

2024-12-06 18:33 UTC, elias75015 requested changes
Problème sur le nom affiché. D'autres tests en cours

2024-12-06 18:37 UTC, elias75015 commented
Comportement innatendu :

- Onglet 1 : je me connecte
![image](https://github.com/user-attachments/assets/1be0884b-87bf-4242-bc7e-8953d48696a2)

- Onglet 2 (nouvel onglet)
![image](https://github.com/user-attachments/assets/6c16635a-2d2a-472b-8234-7886a765980d)

- Onglet 2 : je clique sur "se connecter"
![image](https://github.com/user-attachments/assets/607c95f1-5bc1-47d7-8b88-2ceae22c4696)


Je suis directement connecté sans avoir à entrer mon id + password.

Si c'est le comportement attendu, pourquoi ne pas directement avoir le header en mode connecté quand on arrive sur l'onglet 2 ?

2024-12-06 19:44 UTC, elias75015 commented
Après une heure d'inactivité, toujours connecté

2024-12-06 20:23 UTC, lowzonenose commented
Bon, y'a sûrement des trucs à revoir. 
Comportement difficile à reproduire...
As tu tester sur cette branche ou avec un merge avec main ?

2024-12-07 12:01 UTC, elias75015 commented
Sur la branche telle qu'elle, sans merge

2024-12-07 16:30 UTC, lowzonenose commented
> Problème sur le nom affiché

Difficile à reproduire sans exception

> Plusieurs onglets si on est déjà connecté

Fix mis en place,
on change le stockage, la **sessionStorage** par le **localStorage**, car la session ne semble pas faire son job

> Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid base URL
    at s (@badgateway_oauth2-client.js?v=179d4223:16:18)
    at t2.OAuth2Client.getEndpoint (@badgateway_oauth2-client.js?v=179d4223:62:54)
    at t2.OAuth2AuthorizationCodeClient.getAuthorizeUri (@badgateway_oauth2-client.js?v=179d4223:168:108)
    at PluginServices.getAccessLogin (ServiceConnection.js:60:64)

Difficile à reproduire.
L'exception semble dire que le **sso** n'est pas atteint pour une raison inconnue

2024-12-09 11:10 UTC, elias75015 approved these changes

2024-12-09 11:12 UTC, azarz commented
Pas possible de tester pour moi avant vendredi désolé...

2024-12-09 14:14 UTC, IGNFhc approved these changes
Pas de problèmes particuliers de mon côté. 
Je n'ai pas beaucoup d'idées de scénario de test

2024-12-18 14:10 UTC, closed without merging