paage d'impression
IGNF/cartes.gouv.fr-entree-carto pull request #379
Opened 2024-11-07 14:14 UTC by IGNFhc

## Pull request checklist

Verifiez que votre Pull Request remplit les conditions suivantes :
- [ ] Des tests ont été ajoutés pour les changements (corrections de bugs ou features)
- [ ] De la documentation a été mise à jour ou ajoutée si nécessaire (corrections de bugs ou features)
- [ ] Un build (`npm run build`) a été lancé localement et s'est correctement déroulé
- [ ] Les exemples impactés par les modifications (`npm run samples`) ont été testés et validés localement
- [ ] Les tests (`npm run test`) sont passés localement

## Type de Pull request

 

 

Quel type de changement cette Pull Request introduit-elle :
- [ ] Bugfix
- [ ] Feature
- [ ] Mise à jour du style du code (syntaxe, renommage de fonctions)
- [ ] Refactoring (lisibilité/performance du code, sans changements fonctionnels)
- [ ] Changement sur le processus de build
- [ ] Contenu de la documentation
- [ ] Autres (décrire ci-après) : 

## Quel est le comportement actuel (avant PR) :

Numéro du ticket : N/A

## Quel est le nouveau comportement :

-
-
-

## Cette PR introduit-elle des breaking changes ?

- [ ] Oui
- [ ] Non

## Autres informations

2024-11-12 16:33 UTC, IGNFhc commented
TODO : 
- [ ] gestion portrait / paysage
- [ ] gestion des marges
- [ ] export PDF
- [ ] impression

2024-11-20 18:15 UTC, azarz commented
La classe ! Résolution d'un problème vieux de 10 ans.

2024-12-02 13:53 UTC, elias75015 commented
@IGNFhc stp tu pourras résoudre les conflits sur la branche et dédraftiser avant review officielle ?

2024-12-03 09:40 UTC, IGNFhc commented
C'est bon

2024-12-03 18:52 UTC, elias75015 requested changes
Tout est OK sauf la position du bouton en mode mobile.

![image](https://github.com/user-attachments/assets/a08d7c85-2b1b-4cdf-a2bc-8306218ec45e)

En fait, je pense qu'on peut désactiver la fonctionnalité en mode mobile.

2024-12-04 07:30 UTC, azarz commented
Possible de le faire en CSS, si tu veux je m'en occupe @IGNFhc

2024-12-04 07:35 UTC, IGNFhc commented
Je veux bien Amaury merci ☺️

2024-12-05 08:40 UTC, azarz commented
> En fait, je pense qu'on peut désactiver la fonctionnalité en mode mobile.
C'est maintenant fait via CSS

2024-12-05 11:29 UTC, elias75015 commented
:+1:

2024-12-05 11:29 UTC, elias75015 approved these changes

2024-12-05 11:41 UTC, merged