Feature/menu tierce
IGNF/cartes.gouv.fr-entree-carto pull request #407
Opened 2024-12-06 10:38 UTC by IGNFhc

## Pull request checklist

Verifiez que votre Pull Request remplit les conditions suivantes :
- [ ] Des tests ont été ajoutés pour les changements (corrections de bugs ou features)
- [ ] De la documentation a été mise à jour ou ajoutée si nécessaire (corrections de bugs ou features)
- [x] Un build (`npm run build`) a été lancé localement et s'est correctement déroulé
- [ ] Les exemples impactés par les modifications (`npm run samples`) ont été testés et validés localement
- [ ] Les tests (`npm run test`) sont passés localement

## Type de Pull request

 

 

Quel type de changement cette Pull Request introduit-elle :
- [ ] Bugfix
- [x] Feature
- [ ] Mise à jour du style du code (syntaxe, renommage de fonctions)
- [ ] Refactoring (lisibilité/performance du code, sans changements fonctionnels)
- [ ] Changement sur le processus de build
- [ ] Contenu de la documentation
- [ ] Autres (décrire ci-après) : 

## Quel est le comportement actuel (avant PR) :

Close https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/386

## Quel est le nouveau comportement :

- ajout d'un menu de fonctionnalités tierces
![bla](https://github.com/user-attachments/assets/cdcaa17b-2098-47e4-94ed-c60b430d0fd3)

## Cette PR introduit-elle des breaking changes ?

- [ ] Oui
- [x] Non

## Autres informations

2024-12-06 17:12 UTC, elias75015 requested changes
- [ ] le bouton du menu doit être en haut à gauche, le bouton du catalogue doit passer en haut à droite (cf maquette ci-dessous)
![image](https://github.com/user-attachments/assets/f7729783-9800-42db-a8ed-971c3bb0a8df)
- [ ] la tooltip au survol sur le bouton du menu ne s'affiche pas au bon endroit (attention à veiller que c'est OK après résolution du point 1) : 
![image](https://github.com/user-attachments/assets/34788d35-56b6-4710-a86c-50eb04dad8fd)
- [ ] le tooltip d'impression a sa flèche cassée. De toute manière, il faut retirer le bouton d'impression et juste le laisser dans le menu des fonctions tierces
![image](https://github.com/user-attachments/assets/13bafad2-f016-4c7b-8248-fe80049fa7ef)
- [ ] le bouton de partage doit être retiré, son entrée dans le menu des fonctions tierces suffit
![image](https://github.com/user-attachments/assets/954a45fe-e66b-4ee3-815a-cb089297ff99)
- [ ] le bouton d'import de donnée doit être retiré, son entrée dans le menu des fonctions tierces suffit
![image](https://github.com/user-attachments/assets/210dec3a-ce97-401c-aca2-ced422053f8e)
- [x] a priori ce sera corrigé via le retrait des boutons (voir ci-dessus) mais quand on ouvre le partage ou l'impression via le menu de fonctions tierces, on a des boutons en surbrillance, et on ne peut pas fermer la fenêtre d'impression (le bouton "fermer" est caché)
![image](https://github.com/user-attachments/assets/1b849171-2f18-4dd4-97dc-c243a06d2f57)
![image](https://github.com/user-attachments/assets/6e106909-6f92-46da-b696-47a171c8e769)

2024-12-09 15:24 UTC, azarz commented
Possible de cacher le bouton via CSS, pour qu'il soit présent mais caché 


De: "IGNFhc" ***@***.***> 
À: "IGNF/cartes.gouv.fr-entree-carto" ***@***.***> 
Cc: "Amaury Zarzelli" ***@***.***>, "Review requested" ***@***.***> 
Envoyé: Lundi 9 Décembre 2024 16:22:04 
Objet: Re: [IGNF/cartes.gouv.fr-entree-carto] Feature/menu tierce (PR #407) 





Pour le bouton d'import de données, comme le DOM est géré côté extension, je n'ai pas la main pour afficher la fenêtre sans qu'il existe. 

— 
Reply to this email directly, [ https://github.com/IGNF/cartes.gouv.fr-entree-carto/pull/407#issuecomment-2528333434 | view it on GitHub ] , or [ https://github.com/notifications/unsubscribe-auth/AEJ4WPAREM64PP6G3YC56L32EWYRZAVCNFSM6AAAAABTEMORQ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMRYGMZTGNBTGQ | unsubscribe ] . 
You are receiving this because your review was requested. Message ID: ***@***.***>

2024-12-09 15:41 UTC, IGNFhc commented
Effectivement ça se fait :see_no_evil:

2024-12-10 17:40 UTC, IGNFhc commented
vous pouvez y aller sur la review @lowzonenose et @elias75015

2024-12-10 18:56 UTC, elias75015 commented
Ok on regarde. Même si validation, attendre mon go avant de merger (recette release en cours)

2024-12-11 17:05 UTC, lowzonenose commented
Je ne sais pas si c'est lié à la PR, mais il manque l'icone de l'import des données :
![image](https://github.com/user-attachments/assets/91cff081-1be0-4dbd-9a53-d7fae2415cd4)

2024-12-11 17:22 UTC, lowzonenose approved these changes

2024-12-11 17:22 UTC, lowzonenose commented on src/components/menu/MenuTierce.vue
> +   * @description
pas sûr que ceci soit la bonne doc

2024-12-11 17:22 UTC, lowzonenose commented on src/components/menu/LeftMenuTool.vue
>  <template>
`id = MenuCatalogueContentClose`  ?

2024-12-12 14:15 UTC, IGNFhc commented
> Je ne sais pas si c'est lié à la PR, mais il manque l'icone de l'import des données : ![image](https://private-user-images.githubusercontent.com/10401006/394844521-91cff081-1be0-4dbd-9a53-d7fae2415cd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMTI1MzIsIm5iZiI6MTczNDAxMjIzMiwicGF0aCI6Ii8xMDQwMTAwNi8zOTQ4NDQ1MjEtOTFjZmYwODEtMWJlMC00ZGJkLTlhNTMtZDdmYWUyNDE1Y2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDE0MDM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NWViNDJkY2FhNjg1Y2Q0NGRiM2M3YzA5YzdkZDdlMTEzZmY4NTVlZWM5MmQ4ZmQxOTNiZGJmY2ZjY2M3NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5XnjnJEwMtFt6I4DgcsSwmLwPjsOp0nQiJLAV1gtwFQ)
> 
> Le bouton d'impression est activable dans le menu des contrôles, mais je ne le vois pas : ![image](https://private-user-images.githubusercontent.com/10401006/394845681-5869c881-9744-4e01-91ae-7bc6e5b24698.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMTI1MzIsIm5iZiI6MTczNDAxMjIzMiwicGF0aCI6Ii8xMDQwMTAwNi8zOTQ4NDU2ODEtNTg2OWM4ODEtOTc0NC00ZTAxLTkxYWUtN2JjNmU1YjI0Njk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDE0MDM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjYjRhMGMyOTc5MjAwZjgxMDE0MDQwZDA0NzI0NzFkNGQ0ZjhmYTJlYWViMDliNTQyOGU2M2Y3YWZkZTA0NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wNFNQ0yz1ogDWEeXrlMS-P-k4b74GCsaP9s7VKu44sA)

2 points résolus

2024-12-12 14:19 UTC, IGNFhc commented on src/components/menu/LeftMenuTool.vue
>  <template>
J'ai pas compris cette remarque

2024-12-12 17:36 UTC, elias75015 commented
- [ ] Mauvais thème pour le bouton fermer (couleur dark alors qu'on est en thème light)

![image](https://github.com/user-attachments/assets/d4e2729b-e0d8-413d-9670-a00409ca6683)

- [ ] Au survol, les icones des boutons Catalogue, Widget, Menu Tierce disparaissent (j'ai cru comprendre que tu espérais l'aide de @azarz sur la question)
![Capture d’écran du 2024-12-12 18-31-27](https://github.com/user-attachments/assets/e9b6f16e-5598-4c11-b45d-6aeefe54da66)
![Capture d’écran du 2024-12-12 18-31-38](https://github.com/user-attachments/assets/a3c4b1f1-6853-4d77-9be4-0f4c7c6946b6)
![Capture d’écran du 2024-12-12 18-31-49](https://github.com/user-attachments/assets/2bd5ec9d-2bbf-47d0-a137-f08950969208)


- [ ] Le menu me parait un peu trop large par rapport à la maquette :

https://www.figma.com/design/s7gqdbxLRzPinQCRcoYXcT/Entr%C3%A9e-carto?node-id=3409-37779&node-type=frame&m=dev
![image](https://github.com/user-attachments/assets/d5cbfc02-3aab-4435-bfd8-d1b3c63ab6d2)

2024-12-12 17:37 UTC, azarz commented
J'arrive demain pour checker les 3 points d'Elias si tu veux @IGNFhc

2024-12-12 19:24 UTC, IGNFhc commented
Oui help pour le css 🙏🏽🙏🏽

2024-12-13 10:20 UTC, azarz commented
J'ai poussé du css @IGNFhc @elias75015

2024-12-13 10:57 UTC, elias75015 commented
Tout est OK. Dernière modif (déso j'avais pas vu) : retirer la fonctionnalité d'impression du menu en mode mobile

![image](https://github.com/user-attachments/assets/a1c5165f-e302-4b4d-aecc-e6211e2688c6)

2024-12-13 11:40 UTC, azarz commented
c'est fait

2024-12-13 13:05 UTC, elias75015 approved these changes
C'est OK pour moi.

NE PAS merger svp, en attente de finalisation de la recette en cours. 

D'ailleurs, il faudrait retirer l'entrée "Mes enregistrements" avant de rapatrier sur main, cette entrée sera ajoutée par JP sur la partie Connexion.

2024-12-13 13:33 UTC, IGNFhc commented
> C'est OK pour moi.
> 
> NE PAS merger svp, en attente de finalisation de la recette en cours.
> 
> D'ailleurs, il faudrait retirer l'entrée "Mes enregistrements" avant de rapatrier sur main, cette entrée sera ajoutée par JP sur la partie Connexion.

Commenté

2024-12-17 09:53 UTC, merged