fix(header): ajout entrée cartes dans header
IGNF/cartes.gouv.fr-entree-carto pull request #440
Opened 2024-12-18 17:35 UTC by elias75015

## Pull request checklist

Verifiez que votre Pull Request remplit les conditions suivantes :
- [ ] Des tests ont été ajoutés pour les changements (corrections de bugs ou features)
- [ ] De la documentation a été mise à jour ou ajoutée si nécessaire (corrections de bugs ou features)
- [x] Un build (`npm run build`) a été lancé localement et s'est correctement déroulé
- [ ] Les exemples impactés par les modifications (`npm run samples`) ont été testés et validés localement
- [ ] Les tests (`npm run test`) sont passés localement

## Type de Pull request

 

 

Quel type de changement cette Pull Request introduit-elle :
- [x] Bugfix
- [ ] Feature
- [ ] Mise à jour du style du code (syntaxe, renommage de fonctions)
- [ ] Refactoring (lisibilité/performance du code, sans changements fonctionnels)
- [ ] Changement sur le processus de build
- [ ] Contenu de la documentation
- [ ] Autres (décrire ci-après) : 

## Quel est le comportement actuel (avant PR) :

Le header de l'entrée carto n'est pas iso avec le header des autres briques de cartes.gouv

entree carto :
![image](https://github.com/user-attachments/assets/4f142bf4-6cef-47f8-80df-3575baab6f41)

autre : 
![image](https://github.com/user-attachments/assets/00c7629e-5401-4166-92fe-01edff06d1a4)

Numéro du ticket : fixes #432 

## Quel est le nouveau comportement :
On ajoute l'entrée "cartes" pour être iso
![image](https://github.com/user-attachments/assets/0c8917d5-c66d-4e62-8613-5245f270393d)

## Cette PR introduit-elle des breaking changes ?

- [ ] Oui
- [x] Non

2024-12-18 23:22 UTC, lowzonenose requested changes

2024-12-18 23:22 UTC, lowzonenose commented on src/views/Main.vue
> +    to: `${useBaseUrl()}`,
hummm..., ce lien doit pointer vers la page actuelle, cad la page d'accueil de l'entrée carto ?
si, oui, pourquoi ne pas mettre tout simplement la route '/' !
ceci permet d'éviter une redirection vers un autre domaine 

cf. https://docs.vue-ds.fr/types#dsfrnavigation-et-tous-les-enfants

2024-12-19 10:29 UTC, lowzonenose commented on src/views/Main.vue
> +    to: `${useBaseUrl()}`,
j'ai mis à jour la démo _github_  pour te montrer où pointent les liens du menu header

2024-12-19 15:31 UTC, elias75015 commented
OK c'est mis à jour

2024-12-19 15:56 UTC, lowzonenose approved these changes
ça devrait le faire

2024-12-19 16:13 UTC, merged